awslabs/shuttle

src/lib.rs
I think my editor broke these at some point.
---
=> Fix doc links

tests/demo/bounded_buffer.rs
This test was written before we had support for data non-determinism.
Now that we do, we can get rid of the outer loop and select parameters
inside the test.
---
=> Simplify bounded buffer example with data non-determinism

src/sync/condvar.rs
=> Fix a doc typo

CHANGELOG.md, Cargo.toml
=> Release v0.0.2

Cargo.toml, src/runtime/thread/continuation.rs
Addresses https://rustsec.org/advisories/RUSTSEC-2020-0151.html
---
=> Bump `generator` to 0.7.0

src/lib.rs, src/scheduler/replay.rs
This new function constructs a `ReplayScheduler` from a file containing
an encoded schedule, in turn allowing us to pass custom configuration
into a `Runner` being used to replay from a file.
Fixes #17.
---
=> Add `ReplayScheduler::new_from_file`

CHANGELOG.md, Cargo.toml
=> Release v0.0.3

src/runtime/execution.rs, src/runtime/task/mod.rs, src/thread.rs, tests/basic/thread.rs
=> Implement thread::current()

CHANGELOG.md, Cargo.toml
=> Release v0.0.5

src/sync/atomic/mod.rs
=> Fix a Clippy lint

.github/workflows/tests.yml, src/scheduler/pct.rs
=> Fix a doc issue and add docs to CI

src/runtime/runner.rs
`Runner::run` already needs to construct an `Arc` of the function to test. Should we avoid the construction of `Arc<Arc<_>>` via the `PortfolioRunner`? E.g., by creating a helper run function in `Runner` that can take an existing `Arc`.
---
=> Remove `Clone` bound from `PortfolioRunner::run`

tests/basic/atomic.rs
=> Fix new Clippy lint

CHANGELOG.md, Cargo.toml
=> Release v0.0.7

src/sync/condvar.rs, tests/basic/condvar.rs
The timeout variant has the same caveat as `Condvar::wait_timeout`: we
don't currently test the timeout case, so these methods will always
succeed.
---
=> Implement `Condvar::wait_while` and `Condvar::wait_timeout_while`

Cargo.toml, src/runtime/runner.rs, src/sync/mutex.rs, tests/asynch/basic.rs, tests/asynch/channel.rs, tests/asynch/countdown_timer.rs, tests/asynch/waker.rs, tests/basic/atomic.rs, tests/basic/barrier.rs, tests/basic/clocks.rs, tests/basic/condvar.rs, tests/basic/dfs.rs, tests/basic/execution.rs, tests/basic/mpsc.rs, tests/basic/mutex.rs, tests/basic/once.rs, tests/basic/panic.rs, tests/basic/pct.rs, tests/basic/portfolio.rs, tests/basic/replay.rs, tests/basic/rwlock.rs, tests/basic/shrink.rs, tests/basic/thread.rs, tests/basic/timeout.rs, tests/data/random.rs, tests/demo/bounded_buffer.rs, tests/mod.rs
=> Fix new Clippy lint, test-env-log, and a little code cleanup

src/sync/mutex.rs, src/sync/rwlock.rs
This is to match the standard library, which doesn't require the
contents of a lock to be `Sized`.
---
=> Remove implicit `Sized` bounds on `Mutex` and `RwLock`

CHANGELOG.md, Cargo.toml
=> Release v0.5.0

CHANGELOG.md, Cargo.toml
=> Release v0.6.1

tests/future/basic.rs, tests/future/countdown_timer.rs
=> Fix new clippy redundant_async_block findings

src/lazy_static.rs, tests/basic/lazy_static.rs
=> Fix panic while panicking in lazy_static drop handler

src/runtime/task/mod.rs
=> Remove stale TODO for TaskSet

src/runtime/execution.rs
=> Update deadlock message to print task tag

src/scheduler/replay.rs
=> Fix typo in ReplayScheduler

CHANGELOG.md
- **Add changelog for 0.7.0**
---
=> Add changelog for 0.7.0

tests/basic/mutex.rs
The Shuttle version of `Mutex` is indeed unfair, but no test catches this if it isn't. This PR adds such a test. (I want this in preparation for rewriting `Mutex` on top of batch semaphore.)
=> Add test to check that stdlib mutex is unfair

src/sync/mutex.rs, src/sync/rwlock.rs
Reimplements `std::sync::RwLock` using batch semaphore.
---
=> `std::sync::RwLock` using batch semaphore

src/future/batch_semaphore.rs, src/sync/mutex.rs, src/sync/rwlock.rs
=> Clippy lints

CHANGELOG.md, Cargo.toml
=> Release v0.8

shuttle/src/runtime/execution.rs
This PR changes the internal implementation of the `schedule` function to improve performance without changing functionality. Instead of creating a new `SmallVec` on each call to schedule with the runnable tasks, we use a single `Vec` whose capacity is reused on each call. As a result we only have `O(logN)` allocations where `N` is the maximum number of runnable tasks. Notably there is some limited use of `unsafe` to avoid lifetime issues with references being iteratively added and removed to the persistent vector at each scheduling point.
There is also some other minor cleanup of `schedule` rolled into this change to avoid iterating over the set of tasks more than once etc.
Using the micro-benchmarks added in #189 we see performance improvements of ~10-20% for the scheduling heavy …
=> Persistent Vec to avoid alloc'ing runnable tasks on each schedule

shuttle/src/sync/once.rs
Been seeing a few of the following issues after #188:
```
thread '<unnamed>' panicked at /local/TodWorker-nobody/testruns/57c7ab17-05bc-4f8a-b6b2-d92ed4639d1a/env/brazil-rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cell/once.rs:296:66:
reentrant init
stack backtrace:
0:     0x55ea5b824f92 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h67e4df710c8f676f
1:     0x55ea5b84ff93 - core::fmt::write::hda312f67a39af703
2:     0x55ea5b820c13 - std::io::Write::write_fmt::h8e8a8b40c8cd6968
3:     0x55ea5b824de2 - std::sys::backtrace::BacktraceLock::print::h9ec8308d922515db
4:     0x55ea5b82686c - std::panicking::default_hook::{{closure}}::hd92428497bc2c49c
5:     0x55ea5b82666f - …
```
=> Fix: make Once thread safe
