Cargo.toml
src/lib.rs
src/runtime/execution.rs
src/runtime/failure.rs
src/runtime/mod.rs
src/runtime/runner.rs
src/sync/mutex.rs
src/sync/rwlock.rs
src/thread.rs
tests/basic/replay.rs
tests/data/random.rs
tests/mod.rs

Large tests can produce failing schedules that are too unwieldy to
copy/paste into a call to `replay`. This change adds a new configuration
that can instead write schedules out to a file in a chosen directory.
When this option is enabled, failure messages instead print the name of
the file the schedule was saved to. Failing schedules saved in a file
can be replayed with a new `replay_from_file` convenience function.
The default config remains printing schedules to stdout/stderr, as this
seems like the best fit for use in CI pipelines, where the failing
schedule can be printed in the log file rather than needing to recover a
file from the build server.x
---

Add option to persist schedules to a file

---

src/runtime/execution.rs

This is a frequent short-lived allocation of a new Vec on every context
switch, when we can optimistically use a SmallVec instead. Removing this
allocation makes our benchmarks anywhere from 50-150% faster
(admittedly, the benchmarks context switch more frequently than real
code, so this is a best case).
---

Remove an allocation from ExecutionState::schedule

---

src/scheduler/metrics.rs
tests/basic/metrics.rs
tests/basic/mod.rs

If a `MetricsScheduler` gets dropped without running, the Drop handler
triggers an underflow in its `info!` call. This only happens if an interested
subscriber is registered. This change adds some basic tests that validate
the `MetricsScheduler` is generating the right values, including in the
Drop case.
---

Add some basic tests for metrics and fix an underflow

---

tests/basic/condvar.rs
tests/basic/rwlock.rs

- producer_consumer_random can now use shuttle::rand to generate random
parameters on every iterations, so the outer loop can go away. The diff looks
big because of the indentation change.
- two_readers_and_one_writer can run the writer on the main thread, which
dramatically reduces the search space for DFS
---

Speed up two slow tests

---

src/lib.rs
src/runtime/execution.rs
src/runtime/task/mod.rs
src/scheduler/pct.rs
src/sync/mpsc.rs
src/sync/mutex.rs
src/sync/rwlock.rs
tests/basic/config.rs
tests/basic/mpsc.rs

Previously, we required users to specify (via the `max_tasks` parameter in the `Config`) the maximum number of tasks that could be spawned during an execution.  This change lifts that restriction, and allows spawning of an arbitrary number of tasks.
Note: The PCT scheduler still only supports creation of upto 16 tasks.  A forthcoming PR will update PCT to also support spawning of an arbitrary number of tasks.
---

Allow spawning of an arbitrary number of tasks.

---

src/asynch.rs
src/runtime/execution.rs
src/runtime/runner.rs
src/scheduler/dfs.rs
src/scheduler/metrics.rs
src/scheduler/mod.rs
src/scheduler/pct.rs
src/scheduler/random.rs
src/scheduler/replay.rs
src/scheduler/round_robin.rs
src/thread.rs
tests/asynch/mod.rs
tests/asynch/pct.rs
tests/basic/execution.rs
tests/basic/pct.rs

Tasks that implement busy-wait loops or other infinite loops are a fairness
issue for schedulers like PCT, which will run a thread indefinitely until it
blocks. This change makes both sync and async versions of `yield_now` act as
a hint to the scheduler that the current task should be deprioritized. Only
the PCT scheduler acts on this hint, by moving the current task to the lowest
priority. We could also make the DFS scheduler react to this hint by not
allowing it to re-schedule the current task immediately, but that would be
unsound.
---

Add hints to `yield_now` to allow schedulers to deprioritize a yielding thread

---

Cargo.toml
src/scheduler/pct.rs
tests/basic/pct.rs

PR#16 added support for spawning an arbitrary number of tasks, but the PCT scheduler still required the number of tasks to be specified statically (hardcoded to 16).  This PR extends the PCT scheduler to support an arbitrary number of tasks.  The main idea is that whenever a new task is seen, it is assigned an arbitrary priority.
---

Update PCT scheduler to support an arbitrary number of tasks.

---

src/runtime/execution.rs
src/runtime/runner.rs

The level of the span determines when it will be included in tracing output:
a span at level TRACE will only be included in messages at level TRACE, a span
at level INFO will be included in messages at level INFO or lower, etc. So we
want to put these spans at level ERROR to include them in *all* output. The
idea is that Shuttle users can use e.g. `tracing::info!` in their program to
debug, and those messages will include the span info (most importantly, the
task ID) from Shuttle.
---

Use Level::ERROR for all tracing spans

---

src/lib.rs
src/runtime/runner.rs
tests/asynch/pct.rs
tests/basic/mod.rs
tests/basic/pct.rs
tests/basic/timeout.rs

In some applications, we want to run Shuttle for as many iterations as
possible within some time budget to increase our confidence in the
code's correctness. This change adds a new `max_time` config that will
end a test once the timeout is reached. The timeout is only checked
between test iterations, so it won't abort midway through a single test
iteration.
To help guard against slow tests, `Runner::run` now returns the number
of iterations it ran. In normal operation this will be whatever number
of iterations the scheduler dictated (e.g., through `max_iterations`
options), but if the timeout is reached it may be smaller. Callers can
check this value to make sure the test wasn't unreasonably slow.

Add a timeout option to Config

---

src/sync/mutex.rs
tests/basic/mutex.rs
tests/basic/rwlock.rs

We already had `RwLock::into_inner` and this is the same thing. Also
wrote tests for both `into_inner`s.
---

Implement `Mutex::into_inner`

---

Cargo.toml

We're using `rand::seq::index`, which turns out to require the `alloc`
feature of that crate, but the documentation doesn't specify that. This
has been causing some funkiness in builds of packages that depend on
Shuttle, so let's just fix it here. To be honest, I don't even remember
why we turned off the default features for rand to start with---we
certainly don't expect Shuttle to work in `no_std` environments.
---

Include default features for `rand`

---

src/runtime/execution.rs
src/runtime/runner.rs
tests/basic/mutex.rs

In ba014d6 (#24) we changed our tracing spans to use Level::ERROR, but that
had an unexpected side effect: tracing's default env filter includes the
ERROR level, so these spans are always constructed even when we don't
actually want/see any log output. That has a massive performance impact
on large tests, so we need to fix that.
This change instead sets a new hierarchy where all Shuttle's internal
tracing events are at Level::TRACE, and its spans and metrics outputs
are at Level::DEBUG. This means clients can still see our spans without
seeing our tracing output, and also avoids constructing any spans in the
common case where no tracing output is desired.
---

Partially revert some `tracing` changes and make a few more

---

src/sync/mod.rs
src/sync/mpsc.rs
src/sync/mutex.rs
src/sync/rwlock.rs
tests/basic/mod.rs
tests/basic/panic.rs

A common pattern in Rust code is to acquire a lock in a `Drop`
implementation, e.g. to return a resource to a shared pool when dropped.
If code panics while holding that same lock, the Drop handler will try
to enter the lock during unwinding, but the lock is poisoned. In real
Rust code that usually creates a double-panic (`.lock().unwrap()` will
fail). In Shuttle test code it's also a double panic, but the second
panic exposes an unhelpful error about internal Shuttle state.
This change propagates the poison status of `Mutex`s and `RwLock`s so
that the second panic in this scenarios is more helpful and looks the
same as in regular Rust code. To do this, we change where some of the
bookkeeping happens in the `Drop` impls for lock guards, so that the
lock is returned to a usable state. …

Better handling for poisoned locks

---

Cargo.toml
benches/counter.rs
src/lib.rs
src/sync/atomic/bool.rs
src/sync/atomic/int.rs
src/sync/atomic/mod.rs
src/sync/atomic/ptr.rs
src/sync/mod.rs
tests/basic/atomic.rs
tests/basic/mod.rs

This change adds support for the `std::sync::atomic` module.
Sequentially consistent atomics are easy for us to model---we get
sequential consistency for free by just remembering the current value of
each atomic variable. We don't have a way to model other relaxed atomic
behaviors though. This change chooses to treat *all* atomic operations
as if they were SeqCst, and emits a warning the first time it encounters
non-SeqCst atomic operations.
The implementation here is almost certainly too conservative about
inserting context switches between atomic operations. In the future, we
should convince ourselves about which context switches are necessary and
remove the unnecessary ones. That would be a breaking change since it
would invalidate previously recorded scehdules.
---
By submitting this …

Implement SeqCst atomics

---

src/lib.rs
src/runtime/execution.rs
tests/basic/execution.rs

This is useful, for example, to record a concurrent history for linearizability
checking. The number of context switches essentially serves as timestamp.
---

Add function to get the number of context switches in the current execution

---

src/lib.rs
src/runtime/execution.rs
src/runtime/task/clock.rs
src/runtime/task/mod.rs
src/sync/atomic/mod.rs
src/sync/barrier.rs
src/sync/condvar.rs
src/sync/mpsc.rs
src/sync/mutex.rs
src/sync/rwlock.rs
src/thread.rs
tests/basic/atomic.rs
tests/basic/clocks.rs
tests/basic/mod.rs
tests/basic/mpsc.rs
tests/basic/pct.rs

This change adds support for tracking causality among thread operations.
We do this in the standard way, by associating a vector clock with each thread.
The i'th element of a thread's vector clock denotes its knowledge of the clock
of thread i. Clocks are partially ordered using a pointwise ordering <.
The main property we want is that for any pair of events p, q:
(p causally precedes q)  iff  (clock at p  <  clock at q).
We update the code for thread spawn and join, as well as the various synchronization
objects (Atomics, Barriers, CondVars, Mutexes, RwLocks and mpsc channels) to track
causality by updating vector clocks appropriately.
This change does not currently properly track causality for async interactions;
those will be done in a subsequent PR.
---
By submitting this pull …

Add support for tracking thread causality.

---

src/runtime/execution.rs
src/runtime/failure.rs
tests/basic/panic.rs

Double panics are a common problem in concurrent Rust code. For example,
a thread might panic while holding a lock, and then need to acquire that
lock again during stack unwinding, but the lock is already poisoned. In
these cases, Shuttle currently can't print the schedule that led to the
original panic, because the double panic aborts the process before our
`catch_unwind` has a chance to run.
This change adds a new panic hook that gets a chance to run before the
double panic happens. We use this hook to print the schedule, so that
even if we double panic in future at least the user gets some output
they can use to reproduce the problem. There's some trickiness here
(outlined in a module comment for `failure.rs`) around running different
panic handlers at different times, which makes the …

Print a failing schedule even during double panics

---

CHANGELOG.md
Cargo.toml

Also removing the `authors` field, which is being deprecated by crates.io.
---

Release v0.0.6

---

src/runtime/execution.rs
tests/basic/execution.rs

This happens most often if you try to access a Shuttle primitive from
outside a Shuttle test. Rather than spewing an opaque error message
about a thread local not being set, let's give a somewhat meaningful
error message about what probably went wrong.
---

Give a better error message when ExecutionState is inaccessible

---

src/asynch.rs
src/lib.rs
src/runtime/task/mod.rs
src/thread.rs
tests/basic/thread.rs

Thread local storage allows threads to create slots using `LocalKey`,
which is instantiated using the `thread_local` macro. The objects in
these slots have their destructors run when the corresponding thread
exits.
Rust's TLS implementation leaves a lot of decisions either "best effort"
or platform-defined, so we have some degrees of freedom here. We model
something roughly like the fast-path Unix implementation: we allow TLS
destructors to initialize other TLS slots, but prevent re-initialization
of any TLS slot that has already been destroyed. We do run TLS
destructors on the main thread before it exits.
This implementation is based on Loom's TLS implementation, but we have a
little richer support for destructors (shown in the `drop_init` test).
---
By submitting this pull request, I …

Add LocalKey and thread local storage

---

src/asynch.rs
src/runtime/execution.rs
src/runtime/task/mod.rs
src/runtime/task/waker.rs
tests/asynch/basic.rs
tests/asynch/channel.rs
tests/asynch/countdown_timer.rs

When an async task's `JoinHandle` is dropped, we mark the task as dropped. Dropped tasks are not allowed to force a deadlock, meaning that execution can end successfully when all tasks are either finished or dropped. At the same time, dropped tasks should still be runnable by the executor so long as some non-dropped task has not finished.
---

Implement `Drop` for async task `JoinHandle`

---

src/asynch.rs
src/runtime/task/mod.rs
tests/asynch/basic.rs

Currently, Shuttle does not allow a waiter to be set for a task if a waiter already exists. This may cause a problem when the waiting task wakes itself.
Additionally, it's possible for a waiter to be set for a task, then have the waiter finish before the other task resumes. This happens whenever the waiter wakes itself up. This PR fixes that issue by only waking async waiting tasks when they are blocked.
---

Fix how waiters are set and woken

---

src/asynch.rs
src/runtime/task/mod.rs
tests/asynch/basic.rs

`block_on` is supposed to run a future to completion *on the current
thread*. This is visible in the type signature for `block_on` in other
futures executors, which do not require the future to be `Send`. We were
instead implementing `block_on` using `spawn`, and so required the
future to be `Send`.
This change makes `block_on` truly run the future to completion on the
current thread, by just running poll in a loop (with the appropriate
yield points inserted).
---

Make `asynch::block_on` run on the current thread

---

src/lib.rs
src/thread.rs
tests/basic/thread.rs

Not tally sure what's going on here, but I've seen tests where a single
`thread_local` somehow got multiple versions of a `LocalKey` (one per
callsite). My guess is that we need to make them `static` instead of
just `const`, but I don't really understand why. Making this change at
least forces us to also implement Send/Sync for `LocalKey`, whereas
before the compiler didn't ask for it, which suggests the `LocalKey`s
weren't being shared like we expected them to be.
I wasn't able to write a test that actually exposed the buggy behavior,
though -- I can only reproduce it in a release build, which suggests it
might be a codegen problem or something.
---

Fix thread_local to actually be static

---

src/runtime/execution.rs
src/runtime/mod.rs
src/runtime/storage.rs
src/runtime/task/mod.rs
src/sync/mod.rs
src/sync/once.rs
tests/basic/clocks.rs
tests/basic/mod.rs
tests/basic/once.rs

`Once` is a synchronization primitive often used in a static variable to
ensure some initialization logic runs at most once in the execution of a
program. To ensure that we support this pattern, we implement a new
global storage map that is empied across executions, and use it to
ensure that a `Once` cell's state resets across test executions. This
also means that multiple Shuttle tests running concurrently (e.g., under
the cargo test runner with a default config) will see independent
instances of a static Once cell and be properly isolated from each
other.
The storage map shares common logic with the TLS map we already have, so
this PR factors that map out into a single abstraction.
In a future PR we'll use Once to implement lazy_static, which will also
store its values into the global …

Implement `Once` and generalize thread-local storage map

---

src/asynch.rs
src/runtime/execution.rs
src/runtime/storage.rs
src/runtime/task/mod.rs
src/runtime/task/waker.rs
src/runtime/thread/continuation.rs
tests/asynch/waker.rs

It's possible for a task's waker to be invoked in the middle of a call
to that task's `poll` by the executor. We had accounted for that
possibility if the task called *its own* waker, but that's not good
enough: the waker can escape to other threads that can invoke it before
`poll` finishes (e.g., if the task blocks to acquire a lock).
This change fixes the waker behavior by clarifying the semantics of a
call to `wake`: a task whose waker is invoked should not be blocked
*when it next returns Pending to the executor*, and should be woken if
that has already happened. To do this, we introduce a new `Sleeping`
state for tasks, that has the same semantics as `Blocked` but that is
recognized by waker invocations, which will only unblock a task in
`Sleeping` state. This also removes the …

Fix waker behavior when invoked before a `poll` finishes

---

src/current.rs
src/lib.rs
src/sync/condvar.rs
tests/basic/clocks.rs
tests/basic/execution.rs
tests/basic/mpsc.rs

Just an effort to not pollute the top-level namespace too much. Putting
these into their own module gives us a place to put future functions
that also reveal information about the current execution.
---

Move clock functions into their own module

---

Cargo.toml

This picks up the fix for [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159) in `chrono`.
---

Bump `tracing-subscriber` to v0.3.1

---

src/asynch.rs

This `must_use` is redundant because Rust will already warn about unused
`Future`s.
---

Fix new warning on Rust 1.58.1

---

Cargo.toml

This bump addresses a rustsec issue. I also don't think it's worth pinning minor versions like this—they just create maintenance work for us, and since we're a library, they also end up pulling in extra versions for customers.
---

Bump dependencies and stop pinning minor versions

---

CHANGELOG.md
Cargo.toml

I think the fact that we haven't changed the API in > 6 months suggests it's stable enough for a 0.1.0 release.
---

Release v0.1.0

---

src/sync/mutex.rs
src/sync/rwlock.rs
tests/demo/async_match_deadlock.rs
tests/demo/mod.rs

Currently, if code tries to re-acquire a lock it already holds, it
correctly panics but with an unhelpful error message about Shuttle's
internals. Instead, let's provide a nicer error message about why the
calling code is buggy.
This came up while trying out the super neat example from a
[fasterthanlime blog post], which Shuttle has no trouble finding the
deadlock in, but wasn't giving a helpful error message for.
[fasterthanlime blog post]: https://fasterthanli.me/articles/a-rust-match-made-in-hell
---

Friendlier error messages for re-entrancy failures

---

src/sync/mod.rs

Re-export `std::sync::Weak` (until true `Arc` support is implemented)

---

src/runtime/runner.rs
src/scheduler/mod.rs
tests/mod.rs

Just a couple of small things: removing the `Debug` bound from the `Scheduler` trait, and removing some clippy allows that are now fixed upstream.
---

Small cleanups

---

src/sync/mutex.rs
tests/basic/condvar.rs
tests/basic/dfs.rs
tests/basic/mutex.rs
tests/basic/replay.rs
tests/demo/bounded_buffer.rs

Without `try_lock` it was easier to justify context switches, because
acquire was a right mover (we only needed a context switch before) and
release was a left mover (we only needed a context switch after).
However, with `try_lock` that is not the case anymore. This commit
argues why we need a context switch at the end of `lock` and `try_lock`
(both in the success and failure case), and why we do not need a context
switch at the beginning of `try_lock` and `MutexGuard::drop`.
---

Implement `Mutex::try_lock`

---

src/runtime/task/mod.rs
src/sync/rwlock.rs
tests/basic/clocks.rs
tests/basic/rwlock.rs
tests/demo/async_match_deadlock.rs

This is a little tricky because `std` is unclear about whether a thread
can acquire the same read lock multiple times. For `read` it says:
> This function might panic when called if the lock is already held by
> the current thread.
So acquiring a second read lock _might_ fail. But for `try_read` it says:
> This function will return the WouldBlock error if the RwLock could not
> be acquired because it was already locked exclusively.
suggesting that `try_read` _must_ succeed the second time (the lock is
not held exclusively).
We resolve this ambiguity by choosing a conservative semantics that
always forbids a thread acquiring the read lock twice. This helps us
catch deadlocks, especially in async programs where a task might
nondeterministically migrate between threads and only deadlock if …

Implement `RwLock::{try_read, try_write}`

---

Cargo.toml
src/runtime/thread/continuation.rs
src/scheduler/serialization.rs
tests/asynch/mod.rs

Mostly to pick up the new `generator` version, which fixes a bug with
floating point on aarch64.
---

Rust 2021 conversion and dependency bumps

---

src/hint.rs
src/lib.rs
tests/asynch/mod.rs

The only thing we actually care about here is `hint::spin_loop`, which
we just treat the same way as `yield_now`.
Part of #75.
---

Implement the `std::hint` module

---

Cargo.toml
src/scheduler/serialization.rs
src/sync/atomic/bool.rs
src/sync/atomic/ptr.rs

The maintainer of the `varmint` crate we're using is moving on and would
like to deprecate the crate [[1]], so let's inline a simplified version
for now. I think we should revisit our serialization format soon anyway,
but this will unblock the `varmint` maintainer.
[1]: https://github.com/mycorrhiza/varmint-rs/issues/8
---

Inline a simplified varint implementation

---

CHANGELOG.md
Cargo.toml
src/sync/atomic/mod.rs

We've been getting warnings about `ansi_term` being unmaintained. That's a bit silly as a security advisory, but it's easy enough to switch. We also need to release a new version so we can remove the `varmint` dependency (#82).
---

Remove `ansi_term` and release v0.4.0

---

src/runtime/execution.rs
src/thread.rs
tests/basic/thread.rs

We weren't running the same TLS destructor logic for the main thread as
all other threads. This meant a thread-local on the main thread wouldn't
be dropped until the entire test finished, causing spurious deadlocks or
other confusion.
Fixes #86.
---

Run TLS destructors for the main thread

---

src/future/mod.rs
tests/future/basic.rs

In our code we actually call `abort` method on tokio's `JoinHandle` struct, once I tried to use shuttle, I saw that calling `abort` causes another panic
```bash
...
thread 'main' panicked at 'not implemented', /Users/koshelev/.cargo/registry/src/github.com-1ecc6299db9ec823/shuttle-0.4.1/src/future/mod.rs:42:9
stack backtrace:
```
Not sure if this is the right way to implement it, happy to iterate on that as well as adding more tests if required. I am not confident that `park` used inside the unit test does what I expect (park task , my flaky finder hasn't discovered any issues with it though:
```bash
flaky-finder -j3 -r500 --continue "cargo test --color=always --test mod future::basic::join_handle_abort"
>> Warming up...done.
[00:01:06] [████████████████████████████████████████] (500/500, …
```

Implement abort for JoinHandle

---

Cargo.toml
src/rand.rs
src/scheduler/pct.rs
tests/data/random.rs
tests/demo/bounded_buffer.rs

Projects that use latest version of `rand` crate are largely unable
to use deterministic random generators from shuttle because `RngCore`
and friends are incompatible between the latest version (0.6.4) and version
that Shuttle uses (0.5.1).

Upgrade dependencies

---

src/scheduler/pct.rs
tests/basic/pct.rs

It is a sanity check to have some concurrency in every execution of the test closure. However, in PCT the assertion is really there to prevent an underflow. I'm not convinced that we should add similar assertions to other schedulers.
---

Add descriptive error message when PCT rejects tests without concurrency

---

CHANGELOG.md
Cargo.toml
src/lazy_static.rs
src/lib.rs
src/sync/atomic/mod.rs
tests/basic/lazy_static.rs
tests/basic/mod.rs

This change adds support for the `lazy_static` crate. It's mostly built around a `Once` cell for each static plus some global storage.
---

Implement `lazy_static` support

---

src/runtime/thread/continuation.rs

Instead of creating a single-use, throw-away pool that could mask bugs.
---

Panic when acquiring a continuation with uninitialized pool

---

src/runtime/execution.rs
src/runtime/task/mod.rs
src/sync/barrier.rs
src/sync/condvar.rs
src/sync/mpsc.rs
src/sync/mutex.rs
src/sync/rwlock.rs
src/thread.rs
tests/basic/thread.rs
tests/future/basic.rs

The documentation for `std::thread::park`
(https://doc.rust-lang.org/stable/std/thread/fn.park.html) has the following sentences regarding spurious wakeups:
> The `thread::park` function blocks the current thread unless or
> until the token is available for its thread handle, at which point
> it atomically consumes the token. It may also return spuriously,
> without consuming the token.
The documentation goes on to state:
> Notice that being unblocked does not imply any synchronization with
> someone that unparked this thread, it could also be spurious. For
> example, it would be a valid, but inefficient, implementation to
> make both park and unpark return immediately without doing anything.
Shuttle does not currently implement spurious wakeups for `thread::park`, making it possible for …

Support spurious wakeups for `thread::park`

---

src/sync/barrier.rs
tests/basic/barrier.rs

The Rust standard library documentation for [`sync::Barrier`](https://doc.rust-lang.org/std/sync/struct.Barrier.html) states the following about `Barrier::wait`:
> Blocks the current thread until all threads have rendezvoused here.
> Barriers are re-usable after all threads have rendezvoused once,
> and can be used continuously.  A single (arbitrary) thread will
> receive a BarrierWaitResult that returns true from
> BarrierWaitResult::is_leader() when returning from this function,
> and all other threads will receive a result that will return false
> from BarrierWaitResult::is_leader().
This documentation is a bit ambiguous. It says that "a single thread" becomes the leader after returning from `wait`, but it isn't clear if that means a single thread for the existence of the `Barrier`, or …

Fix an issue with `sync::Barrier` leader selection with reuse

---

src/runtime/failure.rs
src/scheduler/serialization.rs
tests/basic/replay.rs
tests/mod.rs

Failing schedules can be long, and printing them on a single long line can be a problem (e.g., #100).
---

Split schedule output over multiple lines

---

src/runtime/execution.rs
src/runtime/runner.rs
src/runtime/task/mod.rs
tests/basic/uncontrolled_nondeterminism.rs

I guess this is easiest described by showing the output. Two lines of output with`RUST_LOG=trace` turned on before this change:
```
2023-03-30T01:30:25.407978Z TRACE execution{i=0}:spawn_some_futures_and_set_tag{num_threads=0}:spawn_some_threads_and_set_tag{num_threads=1}:spawn_some_threads_and_set_tag{num_threads=2}:spawn_some_threads_and_set_tag{num_threads=3}:spawn_some_threads_and_set_tag{num_threads=1}:spawn_some_threads_and_set_tag{num_threads=2}:spawn_some_threads_and_set_tag{num_threads=4}:spawn_some_threads_and_set_tag{num_threads=5}:spawn_some_threads_and_set_tag{num_threads=6}:spawn_some_threads_and_set_tag{num_threads=3}:spawn_some_threads_and_set_tag{num_threads=1}:spawn_some_threads_and_set_tag{num_threads=8}:spawn_some_threads_and_set_tag{num_threads=7}:spawn_some_futures_an …
```

Fix tracing spans

---

src/future/mod.rs
tests/future/mod.rs
tests/future/streams.rs

Currently, code using FuturesUnordered has a chance to cause Shuttle to erroneously report a deadlock.
For instance, if we take the following code:
```rust
shuttle::future::block_on(async {
let mut tasks = (0..100).map(|_| spawn(async move {})).collect::<FuturesUnordered<_>>();
while let Some(result) = tasks.next().await {
result.unwrap();
}
});
```
When we call `next()` on a task, that task gets dequeued from the `ready_to_run_queue` inside `FuturesUnordered`. If that task is `Poll::Ready`, then all is fine. If it is `Poll::Pending` (in the case where we call `next()` before the `spawn` has had a chance to execute) however, then the task is never polled again, as we don't wake the associated waker.
This PR seeks to solve this issue by waking the waker, which is stored together with the …

Fix FuturesUnordered

---

Cargo.toml
src/runtime/task/clock.rs
src/runtime/task/mod.rs
src/sync/condvar.rs
src/sync/mutex.rs
src/sync/rwlock.rs

These constructors have been const since Rust 1.63
(https://github.com/rust-lang/rust/issues/93740). It's pretty easy for
us to make them const too, which allows code that relies on them being
const to correctly compile with Shuttle.
The one exception is that HashMap::new isn't const, and our Condvar
implementation uses a HashMap to track waiters. I took the easy way out
and just used a vector as an association list instead -- we shouldn't
expect large numbers of waiters on the same condvar, so this shouldn't
be too inefficient.
---

Make {Mutex, Condvar, RwLock}::new const

---

Cargo.toml
tests/future/streams.rs

We have a test that relies on `FuturesUnordered` implementing `IntoIter`, but this is only the case since 0.3.15 (https://github.com/rust-lang/futures-rs/blob/master/CHANGELOG.md#0315---2021-05-11).
I also refactored the `FuturesUnordered` tests a bit. I would have liked to further refactor to have a single function that takes a closure for the way we await on the `FuturesUnordered`, but async closures are still unstable.
---

Bump `futures` dependency

---

src/future/mod.rs

It makes it a drop-in replacement for tokio::task::JoinError. Currently it is not possible to use with frameworks like `anyhow` because their derived `from` implementation requires `as_dyn_error` method
This implementation is consistent with how Tokio implemented `Display`.
---

Implement Error trait for JoinError

---

tests/basic/uncontrolled_nondeterminism.rs

There is an a bit over 1% chance that the `spawn_random_amount_of_threads_dfs_regular_rand` will fail. This happens when the first and the second run happen to generate the same order of random numbers. This is most common when 0 is generated for both runs (1/10 * 1/10), but there is a small chance it will happen for other sequences as well. This PR changes the test so that it is run 10 times, which decreases the chance of failure to somewhere in the range of $0.01^{10}$ - $0.02^{10}$.
---

Fix spurious test failure in the uncontrolled nondeterminism tests

---

src/future/mod.rs
tests/future/basic.rs

Make Shuttle's `JoinHandle` even more compatible with its Tokio counterpart: https://docs.rs/tokio/latest/tokio/task/struct.JoinHandle.html#method.is_finished
---

Add `is_finished` method to `JoinHandle`

---

src/current.rs
src/runtime/execution.rs
tests/basic/tag.rs

This is most useful for manipulating task tags from within a scheduler
Perhaps a niche use case, but being able to set non-current task tags helps in the case of a custom application-aware scheduler that needs to make decisions based on the info encoded in task tags.
---

Allow getting and setting of task tags for arbitrary task IDs

---

src/scheduler/data/mod.rs
src/scheduler/data/random.rs
src/scheduler/mod.rs

Expose DataSource trait and RandomDataSource implementation outside of the crate.
This helps writing of custom randomized schedulers, and more generally supports the bring-your-own scheduler use case.
If you'd rather I not expose `RandomDataSource` and just expand the visibility of `DataSource` just let me know. Although I figured `RandomDataSource` is a pretty useful implementation to make public.
---

Expose DataSource trait and RandomDataSource implementation

---

src/lib.rs
tests/basic/tag.rs

Fixes warnings reported by clippy (for test code) and cargo doc.  See [failing run](https://github.com/awslabs/shuttle/actions/runs/6462431834).
---

Fixed clippy and doc warnings

---

src/current.rs
src/runtime/execution.rs

The current version of `get_tag_for_task ` requires borrowing the `ExecutionState`. This means the `Tag` cannot be gotten if the `ExecutionState` is already borrowed (such as when doing scheduling). This change makes it possible to get a `Task`'s `Tag` while having a borrow to `ExecutionState`.
---

Enable getting a Task's Tag while inside the ExecutionState

---

src/sync/atomic/mod.rs

Atomics should be `RefUnwindSafe`, and currently they are not. This PR makes them `RefUnwindSafe`.
---

Implement RefUnwindSafe for Atomic

---

Cargo.toml
src/future/mod.rs
tests/future/basic.rs

When a detached future is being cleaned up after the end of an
execution, it won't be able to access the current task's storage any
more. We need to bail out early from the cleanup to avoid a panic.
I also fixed two small issues:
1. We accidentally took a dependency on tracing 0.1.36 by using a value type in a `Span::record` call, despite only specifying an earlier version.
2. The docs weren't building on older smallvec versions because of some const weirdness.
---

Fix dropping TLS for detached futures

---

src/current.rs
src/runtime/execution.rs
src/runtime/task/labels.rs
src/runtime/task/mod.rs
tests/basic/labels.rs
tests/basic/mod.rs
tests/basic/tag.rs
tests/basic/thread.rs

[PR98](https://github.com/awslabs/shuttle/pull/98) added support for associated a single untyped `Tag` with each task and thread.  As we've gained experience with Tags, we've increasingly felt a need to have a mechanism that is both better typed, and allows more than one tag to be associated with tasks. This commit introduces `Labels`, which are inspired by `Extensions` in [the http crate](https://docs.rs/http/latest/http/struct.Extensions.html). Users can attach any set of Labels to a task or thread, with the only caveat being that there can be at most one Label for a given type T.  This is not too onerous a restriction, since one can use the common [newtype idiom](https://doc.rust-lang.org/rust-by-example/generics/new_types.html) to easily work around this.
For tracing, we also provide …

Add support for typed task Labels.

---

Cargo.toml

This is a breaking change from 0.6.1 because we changed `Tag` from a
struct to a label (even though we're about to deprecate it).
---

Release 0.7.0

---

src/runtime/execution.rs

I have preferred this trace for debugging.
Adds `i` into the trace (it was in the span previously, but that implementation was broken. Currently not included as it does not work with `tracing_subscriber::fmt`), and reorders such that `next_task` comes before `runnable`. This fixes the "burying" of the next task which happens currently.
---

Update trace in schedule

---

src/lazy_static.rs
src/runtime/failure.rs
tests/basic/tag.rs

Currently `lazy_static` (the macro) is scoped under `shuttle`, but I believe it should be scoped under `lazy_static`. This makes it scoped under `lazy_static` as well.
---

Reexport lazy_static in lazy_static

---

src/rand.rs

`ThreadRng` is `Clone` in `rand`, so it should be here as well.
---

Impl Clone for ThreadRng

---

src/sync/once.rs

fixes clippy error https://rust-lang.github.io/rust-clippy/master/index.html#new_without_default
---

#[allow(clippy::new_without_default)] for Once

---

src/sync/mpsc.rs
src/sync/mutex.rs
src/sync/rwlock.rs
src/thread.rs
tests/basic/mpsc.rs

Improves the API parity by:
* Expose `panicking` and `Result` from the thread module
* Implement `get_mut` for rwlock & mutex
* Implement `try_send` and iterators for mpsc channels
---

Api parity improvements

---

CHANGELOG.md
Cargo.toml

Mostly to release #120, but also some other small compatibility stuff.
---

Release v0.7.1

---

src/scheduler/serialization.rs

New lint added in 1.79: https://rust-lang.github.io/rust-clippy/master/index.html#/legacy_numeric_constants
---

Clippy 1.79 new lint

---

Cargo.toml
src/future/batch_semaphore.rs
src/future/mod.rs
src/runtime/execution.rs
tests/basic/mod.rs
tests/future/batch_semaphore.rs
tests/future/mod.rs

This adds batch semaphores into Shuttle (not originally implemented by me) as the core primitive to be used for other synchronisation primitives. Vector clocks were added to the batch semaphore to track causality across `acquire`, `release`, and `try_acquire` calls. 
Implementing other primitives using the batch semaphore will thus also cause causality to be tracked. The eventual goal is for primitives to only rely on the API of batch semaphore, without calls to e.g. `ExecutionState`. As a result, batch semaphore and the runtime internals can be pulled out of Shuttle into a separate `shuttle-core` crate, while both the stdlib and tokio primitives can be placed into new sibling crates, `shuttle-stdlib` and `shuttle-tokio`, respectively.
An open question is how to proceed with the crate …

Batch semaphore, causality tracking

---

src/future/batch_semaphore.rs
src/future/mod.rs
src/sync/mutex.rs
tests/demo/async_match_deadlock.rs

Reimplements `std::sync::Mutex` using batch semaphore. The tests already include cases to check causal dependencies and the number of context switches, so these have not changed.
This PR changes `block_on` to not yield before the future is polled for the first time. This caused one replay test to fail. I'm not sure if we should bump versions for this, since it is technically a breaking change for schedules?
We can delay this PR until after we start the crate reorganisation, but this is ready for reviews in any case.
---
While trying to make sure the new semaphore implementation is equivalent to the old one in terms of context switches, I found it useful to write out how the methods work at a high-level, including their yield points. Including this here in case it's useful:
- `Mutex::lock` …

`std::sync::Mutex` using batch semaphore

---

src/future/batch_semaphore.rs
src/sync/barrier.rs

Outputting the `VectorClock` in the debug output just adds noise. Kept it in `Task`, maybe that will want to change as well.
---

Omit vector clock from debug outuput of Waiter

---

src/lib.rs
src/scheduler/random.rs
tests/data/random.rs
tests/mod.rs

- When a failing case is found by `RandomScheduler`, shuttle now reports the random seed being used in addition to the failing schedule.
- This requires a minor change in the implementation of `RandomScheduler`. Now, on a new execution, `RandomScheduler.rng` will be reinitialized with the new seed generated from `data_source`. 
This is necessary because the two RNGs used in `RandomScheduler` (i.e., `rng` and `data_source`), though initialized using the same seed, advances at different paces. Therefore, the two RNGs will most likely be out of sync after the first iteration, and we cannot replay a failure case with just one seed from then. This change synchronizes the two RNGs at each iteration.
This change does not seem to affect the performance of `RnadomScheduler`.
- Support replaying …

Reporting & replaying failing random seeds

---

src/scheduler/uncontrolled_nondeterminism.rs

The update to `Scheduler` making it take `&[&Task]`s instead of `&[&TaskId]`s, made this panic message needlessly verbose. `runnables` is `TaskId`s, and `runnable_tasks` is `Task`s, which makes it hard to discover the difference in tasks.
Updated the panic message to make it easier to spot the difference while at it.
---

Update panic message in UncontrolledNondeterminismCheckScheduler to be less verbose

---

Cargo.toml
src/future/batch_semaphore.rs
tests/future/batch_semaphore.rs

This PR fixes a bug in BatchSemaphore that caused deadlocks in the presence of tasks that gave up waiting for requested permits, under the policy of strict fairness.
---

Fix BatchSemaphore bug causing deadlocks

---

.github/workflows/tests.yml
src/runtime/task/labels.rs
src/sync/rwlock.rs
tests/future/batch_semaphore.rs

Turns out `RwLock` doesn't function correctly when run in release mode, as we don't insert to the readers when there already is a reader. This PR fixes that.
Surprised this hasn't been an issue previously, I guess `RwLock` just isn't used much.
Discovered this when I tried to update the workflow to run the tests in release mode, where some of the `RwLock` tests failed.
This (and similar issues) might explain the instances where we have seen non-replayable schedules generated in release mode and replayed in debug mode, or vice versa.
I should do a pass and check if all tests replay with schedules created in the opposite mode.
---

FIX: Fix RwLock not treating multiple readers correctly in release mode

---

src/current.rs
src/runtime/execution.rs
tests/basic/execution.rs

Adds `reset_step_bound`.
Main motivation is to be able to scale up tests without having a huge step bound.
---

Add `reset_step_count`

---

src/lib.rs
src/scheduler/pct.rs
src/scheduler/random.rs

Does two things:
1. Makes it so that if `SHUTTLE_RANDOM_SEED` is set, then that seed will be used.
2. Makes the PctScheduler also honor `SHUTTLE_RANDOM_SEED` (vs just RandomScheduler previously)
Regarding 2: We added the output seed and replay on seed in https://github.com/awslabs/shuttle/pull/161. @jorajeev originally wanted PCT as well, but this was for some reason left as is. I don't see why PCT shouldn't honor `SHUTTLE_RANDOM_SEED`.
Regarding 1: Currently it is kind of annoying and also just a bad user experience (because we say "set this env var", and then, depending on how the test is setup, might just ignore it) that the test has to use `check_random` for `SHUTTLE_RANDOM_SEED` to be honored. This is made worse by the fact that we mostly don't use `check_random`, and also usually …

Make `SHUTTLE_RANDOM_SEED` always override.

---

Cargo.toml
src/future/mod.rs
src/runtime/execution.rs
src/runtime/task/mod.rs
src/runtime/thread/continuation.rs
tests/basic/thread.rs
tests/mod.rs
tests/ui/spawn_not_send.rs
tests/ui/spawn_not_send.stderr

Adds `spawn_local`. `spawn_local` is like `spawn`, but without the `Send` bound.
---

Add `spawn_local`

---

src/rand.rs
src/runtime/task/mod.rs
src/scheduler/serialization.rs

Currently use of `ThreadRng::default` results in a Clippy error. After this change it does not.
Also fixes some Clippies
---

Fix: make ThreadRng::default no longer give a Clippy error

---

src/future/mod.rs
src/runtime/task/mod.rs

Adds `AbortHandle` (analogous to `tokio::task::AbortHandle`).
---

Add AbortHandle

---

src/runtime/execution.rs
src/runtime/task/mod.rs
src/thread.rs
tests/basic/thread.rs

Adds `thread::scope`, which allows threads to borrow non-'static data.
---
Hello, I’ve been using shuttle in my own projects and found it really useful! I prefer using thread::scope instead of thread::spawn in my code when I can, so I initially vendored Shuttle and added scoped thread support locally.
After seeing #153, I decided to fork and upstream my changes in this pull request. I've included some test cases as well.
One change which may be undesirable is the removal of `Send` bounds from task spawning and changing the functions to take a boxed closure directly. The former was due to scoped threads relying on `Rc<RefCell>` to track the number of running threads. The latter came about because I needed to box the closure early in `spawn_named` (now renamed to `spawn_named_unchecked`) to …

Add thread::scope

---

src/thread.rs

https://doc.rust-lang.org/src/std/thread/mod.rs.html#1822-1824
Currently we just get `Send` and `Sync` as auto traits, which means `JoinHandle<T>` is `Send`/`Sync` only if `T` is `Send`/`Sync`.
---

Impl Send and Sync for JoinHandle<T> regardless of T

---

shuttle/Cargo.toml
shuttle/src/runtime/task/clock.rs
shuttle/src/runtime/task/mod.rs

This PR adds a feature flag for vector clocks to boost Shuttle's testing throughput when they are not needed.
This feature flag is *disabled* by default in production, but *always enabled* for tests because many tests leverage vector clocks for assertions to check correctness. In the micro-benchmarks for the Shuttle repository, this results in performance gains of 5-25%:
[criterion.tar.gz](https://github.com/user-attachments/files/21477778/criterion.tar.gz)
When disabled, the VectorClock struct is replaced by an empty struct for which all operations are i.e. a no-op.
---

Vector Clock Feature Flag

---

shuttle/src/sync/mutex.rs
shuttle/src/sync/rwlock.rs

The latest version of stable has a new warning which fails the `shuttle` build (e.g. https://github.com/awslabs/shuttle/actions/runs/16810934541/job/47617230393?pr=191).
This PR resolves these linter errors.
---

Fix lifetime warnings

---

.github/workflows/tests.yml
shuttle/src/future/mod.rs
shuttle/src/runtime/execution.rs
shuttle/src/runtime/runner.rs
shuttle/src/runtime/task/mod.rs
shuttle/src/thread.rs
shuttle/tests/basic/mod.rs
shuttle/tests/basic/task.rs

This PR adds `TaskSignature`s to the `Task` struct in Shuttle to provide identifiers to tasks that don't change on each iteration of a Shuttle test. These identifiers can be used for debugging with multiple different schedules, for scheduling algorithms to denote specific tasks, and also are a prerequisite for stable *resource identifiers* across Shuttle test iterations.
A signature is intended to distinguish tasks with different behaviors, but is not guaranteed to be unique. To increase the flexibility of the signatures, they provide three methods to distinguish tasks at three levels of granularity: (1) static creation point, (2) dynamic single-task creation context, and (3) dynamic concurrency context. Currently these are instantiated with (1) the location given by the `track_caller` …

Adding stable identifiers to tasks across Shuttle test iterations

---

shuttle/src/runtime/execution.rs
shuttle/src/runtime/task/mod.rs

Prints a backtrace for each task on failure. Uses `RUST_BACKTRACE`/`RUST_LIB_BACKTRACE` to decide whether to capture backtraces (as this is somewhat expensive), which is the same signaling mechanism used by `Backtrace::capture()`.
---

Print task backtraces on deadlock

---

shuttle/src/lazy_static.rs
shuttle/src/lib.rs

Function pointers in `const fn` got stabilized in Rust 1.61.0, which prevented us from doing this before.
---

Make `Lazy` struct fields private

---

shuttle/src/current.rs
shuttle/src/lib.rs
shuttle/src/runtime/execution.rs
shuttle/src/runtime/failure.rs
shuttle/src/runtime/task/mod.rs
shuttle/tests/advanced/abort_freedom.rs
shuttle/tests/advanced/mod.rs
shuttle/tests/basic/panic.rs
shuttle/tests/basic/replay.rs
shuttle/tests/data/random.rs
shuttle/tests/mod.rs

This PR does a few different things, which in a sense is poor PR etiquette, but they also fit together, and I'm not sure splitting it up would have been any better. The general problem being improved upon is that of test panics and aborts, where the goal is to reduce the frequency of test failures with no serialized schedule.
The list of what the PR does:
1. Moves the schedule out of `ExecutionState`. This removes the error mode of not being able to serialize the schedule while `ExecutionState` is borrowed.
2. Removes most of the panic hook and injecting the schedule into the panic payload mechanism. My opinion is that this was hard to follow and reason about, buggy, and didn't provide any significant benefits (the only benefit afaik is that we can read the panic message, ie. what …

Serialize schedule even on aborting panics. Refactor panic path.
